---
title: "hw03"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE, fig.path = 'images/')
```

## HW 03

### 2) Pipelines and Redirection

#### 2.1 
```{bash}
cut -d "," -f 2 nba2017-roster.csv > temporary.txt
sort -u temporary.txt > team-names.txt 
head -5 team-names.txt
rm temporary.txt
```

#### 2.2.
```{bash}
cut -d "," -f 3 nba2017-roster.csv > temporary2.txt
sort -u temporary2.txt > position-names.txt 
head -5 position-names.txt
rm temporary2.txt
```

#### 2.3
```{bash}
cut -d "," -f 7 nba2017-roster.csv | tail +2 | sort | uniq -c | sort -n -r | head -5 > experience-count.txt
head -5 experience-count.txt
```

#### 2.4 
```{bash}
grep "team" nba2017-roster.csv > LAC.csv
grep "LAC" nba2017-roster.csv >> LAC.csv
cat LAC.csv
```

#### 2.5
```{bash}
grep "LAL" nba2017-roster.csv | cut -d "," -f 6 | sort | uniq -c 
```

#### 2.6
```{bash}
grep "CLE" nba2017-roster.csv | wc -l
```

#### 2.7
```{bash}
grep "team" nba2017-roster.csv | cut -d "," -f 1,4,5 > gsw-height-weight.csv
grep "GSW" nba2017-roster.csv | cut -d "," -f 1,4,5  >> gsw-height-weight.csv
cat gsw-height-weight.csv 
```

#### 2.8
```{bash}
grep "team" nba2017-roster.csv | cut -d "," -f 1,8 > top10-salaries.csv
cut -d "," -f 1,8 nba2017-roster.csv | sort -t "," -k 2 -n -r | head -10 >> top10-salaries.csv
cat top10-salaries.csv
```

### Binomial Probability Functions

```{r}
source("code/binomial-functions.R")
first <- bin_probability(10, 3, 1/6)
first
second <- bin_distribution(10, 1/4)
second
plot(second)
third = 0 
for (x in 3:5) {
  third = third + bin_probability(5, x, 0.35)
}
third
fourth <- bin_distribution(15, 0.35)
fourth
plot(fourth)
```

